//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating node {0} - {1}.
        /// </summary>
        internal static string BaseNodeFactory_Create {
            get {
                return ResourceManager.GetString("BaseNodeFactory_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching binary data.
        /// </summary>
        internal static string BinaryDataFrameFilterFactory_MatchDescription {
            get {
                return ResourceManager.GetString("BinaryDataFrameFilterFactory_MatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color string format, should be a hex string in form of #RRGGBB or an X11 color name.
        /// </summary>
        internal static string ColorValue_InvalidStringFormat {
            get {
                return ResourceManager.GetString("ColorValue_InvalidStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set current node to be one from another frame.
        /// </summary>
        internal static string DataFrame_Exception1 {
            get {
                return ResourceManager.GetString("DataFrame_Exception1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only read between 0 and 63 bits from a stream at a time.
        /// </summary>
        internal static string DataReader_InvalidBitCount {
            get {
                return ResourceManager.GetString("DataReader_InvalidBitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primitive type passed to ReadPrimitive - {0}.
        /// </summary>
        internal static string DataReader_InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("DataReader_InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read all requested bytes.
        /// </summary>
        internal static string DataReader_ReadBytesEof {
            get {
                return ResourceManager.GetString("DataReader_ReadBytesEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read a valid character from the stream.
        /// </summary>
        internal static string DataReader_ReadCharEof {
            get {
                return ResourceManager.GetString("DataReader_ReadCharEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only write between 0 and 63 bits from a stream at a time.
        /// </summary>
        internal static string DataWriter_InvalidBitCount {
            get {
                return ResourceManager.GetString("DataWriter_InvalidBitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primitive type passed to WritePrimitive - {0}.
        /// </summary>
        internal static string DataWriter_InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("DataWriter_InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence encountered.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedInvalidEscape {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedInvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trailing backslash in escaped string.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedStringTrailingSlash {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedStringTrailingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown string escape sequence {0}.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedStringUnknownEscape {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedStringUnknownEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must only contain bytes in hex or spaces.
        /// </summary>
        internal static string GeneralUtils_InvalidHexString {
            get {
                return ResourceManager.GetString("GeneralUtils_InvalidHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string must be a multiple of 2 hex characters.
        /// </summary>
        internal static string GeneralUtils_InvalidHexStringLength {
            get {
                return ResourceManager.GetString("GeneralUtils_InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating user config directory.
        /// </summary>
        internal static string GetConfigDir_ErrorCreatingDir {
            get {
                return ResourceManager.GetString("GetConfigDir_ErrorCreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTo not a Int24.
        /// </summary>
        internal static string Int24_InvalidCompareObject {
            get {
                return ResourceManager.GetString("Int24_InvalidCompareObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find DataNode {0}.
        /// </summary>
        internal static string MissingDataNodeException_DefaultMessage {
            get {
                return ResourceManager.GetString("MissingDataNodeException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid endpoint ID {0}.
        /// </summary>
        internal static string NetGraph_InvalidEndpointId {
            get {
                return ResourceManager.GetString("NetGraph_InvalidEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graph must be specified for container.
        /// </summary>
        internal static string NetGraphContainerFactory_MustSpecifyGraph {
            get {
                return ResourceManager.GetString("NetGraphContainerFactory_MustSpecifyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgraph must have a client and server node.
        /// </summary>
        internal static string NetGraphContainerNode_InvalidGraph {
            get {
                return ResourceManager.GetString("NetGraphContainerNode_InvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a client endpoint to go from client to server.
        /// </summary>
        internal static string NetGraphFactory_NoClientEndpoint {
            get {
                return ResourceManager.GetString("NetGraphFactory_NoClientEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a server endpoint to go from server to client.
        /// </summary>
        internal static string NetGraphFactory_NoServerEndpoint {
            get {
                return ResourceManager.GetString("NetGraphFactory_NoServerEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of selected nodes to test against.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_CountDescription {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_CountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} selected nodes.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_DisplayString {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_DisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparion operation.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_OperationDescription {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_OperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config passed for {0} class, using existing value.
        /// </summary>
        internal static string PersistNodeImpl_InvalidConfig {
            get {
                return ResourceManager.GetString("PersistNodeImpl_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read out another line from the stream.
        /// </summary>
        internal static string ReadLine_CountNotReadFromStream {
            get {
                return ResourceManager.GetString("ReadLine_CountNotReadFromStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {0} to unix time, out of range.
        /// </summary>
        internal static string ToUnixTime_CannotConvert {
            get {
                return ResourceManager.GetString("ToUnixTime_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTo not a UInt24.
        /// </summary>
        internal static string UInt24_InvalidCompareObject {
            get {
                return ResourceManager.GetString("UInt24_InvalidCompareObject", resourceCulture);
            }
        }
    }
}
